- name: Install metrics-server using Helm
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Install Helm
    get_url:
      url: https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz
      dest: /tmp
      mode: '755'
    become: yes

  - name: Extract tar in the current directory
    unarchive:
      src: /tmp/helm-v3.6.0-linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes
    become: yes

  - name: Move helm executable to /usr/local/bin
    command: mv /tmp/linux-amd64/helm /usr/local/bin/
    become: yes

  - name: Add bitnami repository and update Helm repo
    command: bash -c "helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update"
    become: no

  - name: Create namespace for metrics-server
    kubernetes.core.k8s:
      kubeconfig: /home/ubuntu/config
      context: kubernetes-admin@cluster.local
      kind: Namespace
      name: metrics

  - name: Install metrics-server
    shell: |
      helm install metrics-server bitnami/metrics-server --namespace kube-system --set apiService.create=true
    environment:
      KUBECONFIG: /home/ubuntu/config






