mariadb:
  primary:
    persistence:
      storageClass: "nfs-storage"
      accessMode: ReadWriteOnce
      size: 8Gi

persistence:
  enabled: true
  storageClass: "nfs-client" # Use the nfs-client StorageClass
  accessMode: ReadWriteOnce
  size: 8Gi

