apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-wordpress
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /srv/nfs/wordpress
    server: 10.0.0.6
