- hosts: k8s_nodes
  gather_facts: no
  become: yes
  tasks:
  - name: Reset kubeadm
    command: kubeadm reset -f
    ignore_errors: yes

  - name: Remove kube config file
    file:
      path: "{{ ansible_env.HOME }}/.kube/config"
      state: absent
    ignore_errors: yes

  - name: Remove kubernetes configuration files
    file:
      path: /etc/kubernetes/*.conf
      state: absent
    ignore_errors: yes

  - name: Flush iptables
    shell: |
      iptables -F
      iptables -t nat -F
      iptables -t mangle -F
      iptables -X
    ignore_errors: yes

  - name: Clear ipvsadm
    command: ipvsadm --clear
    ignore_errors: yes

  - name: Remove etcd data
    file:
      path: /var/lib/etcd/*
      state: absent
    ignore_errors: yes
