apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/ubuntu/ca.crt
    server: https://10.0.0.27:6443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJVWo0d0VwcXBxTmd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBM01qTXhNREV3TVRGYUZ3MHlOREEzTWpJeE1ERXdNVE5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNwQXlzRlg5eFM1eEZmUXQKOXJ4Y25nZDdELzFXdTRRRXNiY25RMkoraGFQeFJhVHhEOUdPempZYWdxNzNCY1JWMjcrTFhVREVKRFNaY3dMcwp6cTZsaEx0NnpWUUtaRnpiRnBzckVyTEh3bmtjUVlRbXRFTlFlSEEvczNVUURMQTRoMmFOSTJtS1ZwSk1ycGkxCk5XTXNXcTJEUU5TTlZxM0xSdEYwM0srYU5XOHBkbHB5Slhpdmd0aTNiMmU0YmZ3QzM4QUVOb2ppcXRZWUVobnYKUFFRbjVka254MDdDQm1vU01GS2hYM21wdm9pU0xpdDdNSGh2b1BMTWxXY0E0THFCdktFUnQvaFJPa0J1bjFWVwp1T1RCNkQrdXFX

- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJVWo0d0VwcXBxTmd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBM01qTXhNREV3TVRGYUZ3MHlOREEzTWpJeE1ERXdNVE5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNwQXlzRlg5eFM1eEZmUXQKOXJ4Y25nZDdELzFXdTRRRXNiY25RMkoraGFQeFJhVHhEOUdPempZYWdxNzNCY1JWMjcrTFhVREVKRFNaY3dMcwp6cTZsaEx0NnpWUUtaRnpiRnBzckVyTEh3bmtjUVlRbXRFTlFlSEEvczNVUURMQTRoMmFOSTJtS1ZwSk1ycGkxCk5XTXNXcTJEUU5TTlZxM0xSdEYwM0srYU5XOHBkbHB5Slhpdmd0aTNiMmU0YmZ3QzM4QUVOb2ppcXRZWUVobnYKUFFRbjVka254MDdDQm1vU01GS2hYM21wdm9pU0xpdDdNSGh2b1BMTWxXY0E0THFCdktFUnQvaFJPa0J1bjFWVwp1T1RCNkQrdXFXekZzUkJFZ0RtbGd3SEJBcTJ6eHBoZkFmcE04TlFOUXZ1bjlJOEVDQWRZSSttZDhCN05jak0xCkVoYjh3d0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUTlk5VldkWVFDZnhrM05FVXRrNkx4bjhmOQpWakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaURXcjlBcmUzR2Vwb2RKZ2hnZm5RSFQ4SG0zY1g5clpxSURrCks0ODg5c1VxTGo2VkN3dlVCdWRIaU01blBnV3oyWGk2RHhoa1pTQ1ZCT1lXWnl0L1pqekZkYU9KNHl2Q3p5SUcKY3pvVStqOWFFaGdVWGZ5RUh2MEJpUlFscjdUOU54RmxIaWYyZFJ3VWtmZUx1K1BsbEdYdWQybnN6cWZqaGZCYwpUYUUzQ0pLempZaFljQUtKRTd5V1hJWmk5OHZ4aEFHRm5XL1VKbld5Ukl0NGhYclpHaW5QRGJ0NDY1UlFMQVNoClBnYlBJQmhlU3JvWDc3UVczVmxVZXBtRXkwb0hVRWhSZHlPc282N1ZmTXVLNGU3N2lITDVvenFybWtsbGVzbEgKTStZSjlkc3B0Y
