- hosts: k8s_nodes
  become: yes
  tasks:
  - name: update all packages
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: update all packages
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"
